package by.epam.model.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Set;

@DynamoDBTable(tableName = "Routes")
public class Route
{
    private String id;
    private String kml;
    private Set<String> tags;
    private String description;
    private String name;
    private String startLocation;

    public Route()
    {
    }

    public Route(String kml, Set<String> tags, String description, String name, String startLocation)
    {
        this.kml = kml;
        this.tags = tags;
        this.description = description;
        this.name = name;
        this.startLocation = startLocation;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId()
    {
        return id;
    }

    @DynamoDBAttribute
    public String getKml()
    {
        return kml;
    }

    @DynamoDBAttribute
    public Set<String> getTags()
    {
        return tags;
    }

    @DynamoDBAttribute
    public String getDescription()
    {
        return description;
    }

    @DynamoDBAttribute
    public String getName()
    {
        return name;
    }

    @DynamoDBAttribute
    public String getStartLocation()
    {
        return startLocation;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public void setKml(String kml)
    {
        this.kml = kml;
    }

    public void setTags(Set<String> tags)
    {
        this.tags = tags;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public void setStartLocation(String startLocation)
    {
        this.startLocation = startLocation;
    }
}
