package by.mjc.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.Set;


@DynamoDBTable(tableName = "Routes")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Route {
    @Getter(onMethod = @__({@DynamoDBHashKey, @DynamoDBAutoGeneratedKey}))
    private String id;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String kml;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String geoJson;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private Set<String> tags;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String description;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String name;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String startLocation;
}
