package by.mjc.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.List;

@DynamoDBTable(tableName = "Routes")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Route {
    @Getter(onMethod = @__({@DynamoDBHashKey, @DynamoDBAutoGeneratedKey}))
    private String id;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String name;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private List<Place> points;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private Position coords;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String imgUrl;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private List<String> tags;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String description;
}
