package by.mjc.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.List;

@DynamoDBTable(tableName = "Routes")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Route {
    @Getter(onMethod = @__({@DynamoDBHashKey, @DynamoDBAutoGeneratedKey}))
    private String id;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String name;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String description;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String length;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String time;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private String imageUrl;
    @Getter(onMethod = @__({@DynamoDBAttribute}))
    private List<Point> points;
}
